apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-master
  namespace: workloads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-master
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: stress-master
    spec:
      containers:
      - name: stress
        image: polinux/stress-ng
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            stress-ng --cpu 1 --cpu-load 25 --vm 1 --vm-bytes 220M --timeout 300s
            sleep 300
          done
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: "2"
            memory: 512Mi
